version: '3'
services:
  mysql:
    image: "mysql:8-oracle"
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=social-media-database
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_USER=social-media-user
      - MYSQL_PASSWORD=dummypassword
